# Generated by Django 5.1.6 on 2025-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
